<?php

namespace Inteco\KuPRa\FridgeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FridgeItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FridgeItemRepository extends EntityRepository
{
}
