<?php

namespace Inteco\KuPRa\DefaultBundle\EntityRepositories;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Session\Session;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
     * @return string
     */
    public function getUserName()
    {
        $session = new Session();
        $user = $this->findOneById($user = $session->get('user'));
        if (!empty($user)){
            return $user->getName() . ' ' . $user->getSurname();
        } else {
            return 'None';
        }
    }
}
